<h3>Getting started</h3>

In [3]:
import numpy as np

In [4]:
arr = np.array([10, 20, 30, 40])
print(arr)
print(type(arr))

[10 20 30 40]
<class 'numpy.ndarray'>


<h3>Print numpy version</h3>

In [9]:
print(np.__version__)

1.26.4


<h3>Check dimension</h3>

In [14]:
a = np.array(42)
b = np.array([1, 2, 3])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


<h3>Array Indexing</h3>

In [19]:
arr = np.array([10, 20, 30, 40])
print(arr[0])
print(arr[0] + arr[3])

10
50


In [21]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(f"The second element of 2nd row is: {arr[1][1]}")

The second element of 2nd row is: 7


In [23]:
arr = np.array([[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]])
print(f"The fourth element of the 3rd row is: {arr[0][2][3]}")

The fourth element of the 3rd row is: 14


<h3>Array Slicing</h3>

In [46]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15])

#Strating from 3 till 6th index 7th index is not included
print("\n",arr[3:7])
#From 8th index to the end
print("\n",arr[8:])
#From start till index 3
print("\n",arr[:4])
#From index 1 till index 9 in 2 steps
print("\n",arr[1:10:2])
#From index 0 till end in 3 steps
print("\n",arr[::3])


 [4 5 6 7]

 [ 9 10 11 12 13 14 15]

 [1 2 3 4]

 [ 2  4  6  8 10]

 [ 1  4  7 10 13]


In [52]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

#Slicing in row 1 from 2nd till index 4
print("\n",arr[0, 2:4])
#Slicing in row 2 from 3nd till index 4
print("\n",arr[1, 3:4])
#Printing 3rd elemet from both rows
print("\n",arr[0:2, 2])
#From both rows printing elements from index 2 till index 4
print("\n",arr[0:2, 2:4])


 [3 4]

 [9]

 [3 8]

 [[3 4]
 [8 9]]


<h3>Array data types</h3>

In [60]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([1.2, 3.5])
arr3 = np.array(["Hi", "ok"])
arr4 = np.array([True, False])

print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)
print(arr4.dtype)

int32
float64
<U2
bool


<h3>Type Casting</h3>

In [63]:
arr = np.array([1.2, 3.5])
newArr = arr.astype("i")
print(newArr)
print(newArr.dtype)

[1 3]
int32


In [65]:
arr = np.array([1, 2, 3, 4])
newArr = arr.astype("str")
print(newArr)
print(newArr.dtype)

['1' '2' '3' '4']
<U11


<h3>Shape and Reshape</h3>

In [70]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)

(2, 3)


In [74]:
arr = np.array([[1, 2, 3], [4, 5, 6]], ndmin = 4)
print(arr.shape)

(1, 1, 2, 3)


In [76]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

#Reshaping array into 3 rows and 4 columns
arr = arr.reshape(3, 4)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [86]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

# Reshape the 1D array into a 3D array with shape (3, 2, 2). This means 3 blocks, each containing 2 rows and 2 columns
arr = arr.reshape(3, 2, 2)
print(arr)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [88]:
arr = np.array([[1, 2, 3], [6, 7, 8]])

#Converting 2D arrat into 1D
arr = arr.reshape(-1)
print(arr)

[1 2 3 6 7 8]


<h3>Concatenating Numpy Arrays</h3>

In [93]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr3 = np.concatenate([arr1, arr2])
print(arr3)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [95]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr3 = np.concatenate([arr1, arr2], axis = 1)
print(arr3)

[[1 2 5 6]
 [3 4 7 8]]


In [97]:
arr1 = np.array([1, 2])
arr2 = np.array([3, 4])
arr3 = np.stack([arr1, arr2])
print(arr3)

[[1 2]
 [3 4]]


In [99]:
arr1 = np.array([1, 2])
arr2 = np.array([3, 4])
arr3 = np.stack([arr1, arr2], axis = 1)
print(arr3)

[[1 3]
 [2 4]]


In [103]:
arr1 = np.array([1, 2])
arr2 = np.array([3, 4])
arr3 = np.hstack([arr1, arr2])
print(arr3)

[1 2 3 4]


In [105]:
arr1 = np.array([[1, 2], [7, 8]])
arr2 = np.array([[3, 4], [5, 6]])
arr3 = np.hstack([arr1, arr2])
print(arr3)

[[1 2 3 4]
 [7 8 5 6]]


In [107]:
arr1 = np.array([1, 2])
arr2 = np.array([3, 4])
arr3 = np.vstack([arr1, arr2])
print(arr3)

[[1 2]
 [3 4]]


In [109]:
arr1 = np.array([[1, 2], [7, 8]])
arr2 = np.array([[3, 4], [5, 6]])
arr3 = np.vstack([arr1, arr2])
print(arr3)

[[1 2]
 [7 8]
 [3 4]
 [5 6]]


<h3>Spliting Array</h3>

In [116]:
arr = np.array([1, 2, 3, 4, 5, 6])
newArr = np.array_split(arr, 2)
print(newArr)
newArr = np.array_split(arr, 5)
print(newArr)

[array([1, 2, 3]), array([4, 5, 6])]
[array([1, 2]), array([3]), array([4]), array([5]), array([6])]


In [126]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newArr = np.array_split(arr, 3)
print(newArr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [130]:
arr = np.array([1, 2, 3, 4, 5, 6])
newArr = np.hsplit(arr, 2)
print(newArr)

[array([1, 2, 3]), array([4, 5, 6])]


In [134]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newArr = np.hsplit(arr, 3)
print(newArr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [136]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newArr = np.vsplit(arr, 3)
print(newArr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


<h3>Transpose</h3>

In [139]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

newArr = np.transpose(arr)
print(newArr)

[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]


<h3>Searching Array</h3>

In [144]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)

(array([3, 5, 6], dtype=int64),)


In [146]:
x = np.where(arr % 2 == 0)
print(x)

(array([1, 3, 5, 6], dtype=int64),)


In [154]:
x = np.searchsorted(arr, 2)
print(x)

1


In [160]:
#In this case it will show that where will be these elements inserted in array
x = np.searchsorted(arr, [6,7,8])
print(x)

[7 7 7]


<h3>Sorting Array</h3>

In [163]:
arr = np.array([[1,3,6], [2,5,4]])
newArr = np.sort(arr)
print(newArr)

[[1 3 6]
 [2 4 5]]


<h3>Filtering Array</h3>

In [166]:
arr = np.array([12,13,14,15])
x = [False, True, True, False]
newArr = arr[x]
print(newArr)

[13 14]


In [170]:
arr = np.array([13, 12, 16, 15, 14, 19, 18, 17, 20])
filterArr = []

for element in arr:
    if element > 15:
        filterArr.append(True)
    else:
        filterArr.append(False)

newArr = arr[filterArr]

print(filterArr)
print(newArr)

[False, False, True, False, False, True, True, True, True]
[16 19 18 17 20]


In [172]:
filterArr = []

for element in arr:
    if element % 2 == 0:
        filterArr.append(True)
    else:
        filterArr.append(False)

newArr = arr[filterArr]
print(newArr)

[12 16 14 18 20]


<h3>Array Operation</h3>

In [177]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

print(arr1 + arr2)
print(np.add(arr1, arr2))

[ 6  8 10 12]
[ 6  8 10 12]


In [179]:
arr1 = np.array([6, 7, 10, 15])
arr2 = np.array([5, 6, 7, 8])

print(arr1 - arr2)
print(np.subtract(arr1, arr2))

[1 1 3 7]
[1 1 3 7]


In [5]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

print(arr1 * arr2)
print(np.multiply(arr1, arr2))

[ 5 12 21 32]
[ 5 12 21 32]


In [7]:
arr1 = np.array([6, 7, 10, 15])
arr2 = np.array([5, 6, 7, 8])

print(arr1 / arr2)
print(np.divide(arr1, arr2))

[1.2        1.16666667 1.42857143 1.875     ]
[1.2        1.16666667 1.42857143 1.875     ]


In [9]:
arr = np.array([2, 3, 4, 5])

print(np.power(arr, 2))

[ 4  9 16 25]


In [17]:
arr = np.array([9, 16, 49, 81])

print(np.sqrt(arr))

[3. 4. 7. 9.]


In [19]:
arr = np.array([4, 6, 5, 2, 1, 3])

print(np.min(arr))

1


In [21]:
print(np.max(arr))

6


In [23]:
print(np.size(arr))

6


In [25]:
print(np.cumsum(arr))

[ 4 10 15 17 18 21]


In [27]:
print(np.cumprod(arr))

[  4  24 120 240 240 720]


<h3>Statictical and Mathematics Function</h3>

In [31]:
arr = np.array([20, 2, 7, 1, 34])

#Mean
print(np.mean(arr))

12.8


In [37]:
#Median
print(np.median(arr))

7.0


In [35]:
#Standard deviation
print(np.std(arr))

12.576167937809991


In [39]:
#Variance
print(np.var(arr))

158.16


In [49]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

#Dot product
arr3 = np.dot(arr1, arr2)
print(arr3)

32


<h3>Random Number Generation</h3>

In [54]:
#Random decomal values

arr = np.random.rand(2, 3)
print(arr)

[[0.83337618 0.60247155 0.07254976]
 [0.12996084 0.99987166 0.12694634]]


In [58]:
#Random integer values

arr = np.random.randint(50, size = (3, 5))
print(arr)

[[12 49 25 37 24]
 [ 3 24 22  0 45]
 [35 11 24 46 40]]


<h3>Types of Array Creation</h3>

In [63]:
#Identity
arr = np.identity(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [73]:
#All zeros
arr = np.zeros([2,3])
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [71]:
#All ones
arr = np.ones([3, 4])
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [105]:
#arange

arr = np.arange(1, 26)
arr = arr.reshape([5,5])
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [111]:
#linspace
arr = np.linspace(1,99, num = 15)
print(arr)

[ 1.  8. 15. 22. 29. 36. 43. 50. 57. 64. 71. 78. 85. 92. 99.]


In [127]:
arr = np.ones([5,5])
zeroArr = np.zeros([3,3])
zeroArr[1][1] = 9
arr[1:4, 1:4] = zeroArr
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
